import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="flex justify-between px-28 py-4 absolute w-full">

          {/* Logo */}
          <div className="flex items-center space-x-3">
            <Image
              src='/favicon.ico'
              width={40}
              height={40}
              alt="Ricardo"
            />
            <div>Cozy Care</div>
          </div>

          {/* Register */}
          <div className="flex items-center">
            <a href="">
              <div className="bg-black text-white px-3 py-2 rounded-xl">
                เข้าสู่ระบบ
              </div>
            </a>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}